<?php
namespace Database\Seeders;
use App\Models\Experiment;use App\Models\InstructionalVideo;use App\Models\Manual;use App\Models\Quiz;use App\Models\User;use Illuminate\Database\Seeder;use Illuminate\Support\Facades\Hash;
class DatabaseSeeder extends Seeder
{
public function run():void{
$admin=User::updateOrCreate(['email'=>env('ADMIN_EMAIL','admin@smartlab.test')],['name'=>'SmartLab Administrator','student_id'=>null,'department'=>'Laboratory Services','role'=>'admin','is_active'=>true,'password'=>Hash::make(env('ADMIN_PASSWORD','SmartLab2026!'))]);
$instructor=User::updateOrCreate(['email'=>'instructor@smartlab.test'],['name'=>'Dr. Amina Bello','department'=>'Applied Sciences','role'=>'instructor','is_active'=>true,'password'=>Hash::make('Instructor2026!')]);
User::updateOrCreate(['email'=>'student@smartlab.test'],['name'=>'Demo Student','student_id'=>'SL/2026/001','department'=>'Agricultural Engineering','role'=>'student','is_active'=>true,'password'=>Hash::make('Student2026!')]);
$co2=Experiment::updateOrCreate(['slug'=>'carbon-dioxide-generation'],['created_by'=>$instructor->id,'title'=>'Carbon Dioxide Generation','category'=>'Chemistry','simulation_type'=>'co2','summary'=>'Investigate stoichiometry, limiting reagents, gas yield and reaction-rate behaviour during the reaction of calcium carbonate with hydrochloric acid.','theory'=>'Calcium carbonate reacts with hydrochloric acid according to CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂. The limiting reagent determines theoretical CO₂ moles. Gas volume is estimated with PV = nRT and an adjustable practical yield.','objectives'=>['Identify the limiting reagent','Calculate theoretical and actual CO₂ yield','Relate temperature and pressure to gas volume','Interpret a gas-volume versus time graph'],'equipment'=>['Reaction flask','Calcium carbonate','Hydrochloric acid','Gas syringe','Thermometer','Digital balance'],'safety_notes'=>['Wear goggles, gloves and a laboratory coat','Hydrochloric acid is corrosive','Do not seal a gas-producing reaction in a rigid closed vessel'],'procedure_steps'=>['Review the manual and video','Set reactant quantities and environmental conditions','Predict the limiting reagent','Run the simulation','Compare theoretical and actual yield','Record observations and submit a report'],'estimated_minutes'=>50,'difficulty'=>'Beginner','is_published'=>true,'accent'=>'cyan']);
Manual::updateOrCreate(['experiment_id'=>$co2->id,'title'=>'CO₂ Generation Laboratory Manual'],['content'=>'## Aim\nGenerate carbon dioxide and analyse stoichiometric yield.\n\n## Governing reaction\nCaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂\n\n## Method\nMeasure reactants, select temperature and pressure, predict the limiting reagent, run the virtual reaction, and compare theoretical with actual yield.\n\n## Report prompts\nExplain the limiting reagent, percentage yield, and the effect of temperature or pressure on calculated gas volume.','version'=>'2.0','is_required'=>true,'is_published'=>true,'sort_order'=>1,'uploaded_by'=>$instructor->id]);
InstructionalVideo::updateOrCreate(['experiment_id'=>$co2->id,'title'=>'Preparing the CO₂ Experiment'],['description'=>'A guided setup and safety orientation.','provider'=>'youtube','url'=>'https://www.youtube.com/embed/6pPSdE5k7zA','duration_seconds'=>420,'is_required'=>true,'is_published'=>true,'sort_order'=>1,'uploaded_by'=>$instructor->id]);
$q=Quiz::updateOrCreate(['experiment_id'=>$co2->id],['title'=>'CO₂ Pre-Lab Quiz','instructions'=>'Score at least 70% to unlock the simulator.','passing_score'=>70,'attempts_allowed'=>5,'duration_minutes'=>15,'is_published'=>true]);$q->questions()->delete();
$q->questions()->createMany([
['question'=>'What is the mole ratio of HCl to CaCO₃?','type'=>'single','options'=>['1:1','2:1','1:2','3:1'],'correct_answer'=>'2:1','explanation'=>'The balanced equation uses two moles of HCl per mole of CaCO₃.','points'=>2,'sort_order'=>1],
['question'=>'Which gas law is used to estimate CO₂ volume?','type'=>'single','options'=>['Boyle only','PV = nRT','Fourier law','Newton cooling law'],'correct_answer'=>'PV = nRT','explanation'=>'The ideal gas relation connects pressure, volume, moles and absolute temperature.','points'=>2,'sort_order'=>2],
['question'=>'Hydrochloric acid should be handled with eye and skin protection.','type'=>'true_false','options'=>['True','False'],'correct_answer'=>'True','explanation'=>'Hydrochloric acid is corrosive.','points'=>1,'sort_order'=>3],]);
$heat=Experiment::updateOrCreate(['slug'=>'fundamentals-of-heat-transfer'],['created_by'=>$instructor->id,'title'=>'Fundamentals of Heat Transfer','category'=>'Thermal Engineering','simulation_type'=>'heat-transfer','summary'=>'Compare conduction, convection and radiation while exploring the influence of material properties, geometry and temperature difference.','theory'=>'Conduction through a plane wall follows Q̇ = kAΔT/L. Convection follows Q̇ = hA(Ts − T∞), while radiation depends on emissivity and absolute temperature to the fourth power.','objectives'=>['Calculate heat-transfer rate','Compare heat-transfer modes','Investigate conductivity and thickness','Interpret energy-time plots'],'equipment'=>['Insulated test section','Temperature sensors','Heater','Material samples','Data logger'],'safety_notes'=>['Treat hot surfaces as hazardous','Allow equipment to cool before handling','Keep liquids away from electrical equipment'],'procedure_steps'=>['Choose a transfer mode','Set geometry and thermal properties','Predict the direction of heat flow','Run the model','Compare material or mode results','Document engineering implications'],'estimated_minutes'=>60,'difficulty'=>'Intermediate','is_published'=>true,'accent'=>'amber']);
Manual::updateOrCreate(['experiment_id'=>$heat->id,'title'=>'Heat Transfer Laboratory Manual'],['content'=>'## Aim\nExplore conduction, convection and radiation using controlled virtual parameters.\n\n## Key equations\nConduction: Q̇ = kAΔT/L. Convection: Q̇ = hAΔT. Radiation: Q̇ = εσA(Th⁴ − Tc⁴).\n\n## Analysis\nCheck SI units, identify the heat-flow direction, compare rate and total energy, and discuss assumptions such as steady state and one-dimensional flow.','version'=>'2.0','is_required'=>true,'is_published'=>true,'sort_order'=>1,'uploaded_by'=>$instructor->id]);
InstructionalVideo::updateOrCreate(['experiment_id'=>$heat->id,'title'=>'Understanding Heat Transfer Modes'],['description'=>'Overview of conduction, convection and radiation.','provider'=>'youtube','url'=>'https://www.youtube.com/embed/7Y3mfAGVn1c','duration_seconds'=>510,'is_required'=>true,'is_published'=>true,'sort_order'=>1,'uploaded_by'=>$instructor->id]);
$q2=Quiz::updateOrCreate(['experiment_id'=>$heat->id],['title'=>'Heat Transfer Pre-Lab Quiz','instructions'=>'Complete the safety and theory check before simulation.','passing_score'=>70,'attempts_allowed'=>5,'duration_minutes'=>15,'is_published'=>true]);$q2->questions()->delete();$q2->questions()->createMany([
['question'=>'For plane-wall conduction, increasing thickness does what to heat-transfer rate?','type'=>'single','options'=>['Increases it','Decreases it','Has no effect','Makes it infinite'],'correct_answer'=>'Decreases it','explanation'=>'Thickness appears in the denominator of Fourier’s plane-wall relation.','points'=>2,'sort_order'=>1],
['question'=>'Which property controls a material’s ability to conduct heat?','type'=>'single','options'=>['Density only','Thermal conductivity','Colour only','Pressure only'],'correct_answer'=>'Thermal conductivity','explanation'=>'Thermal conductivity k directly scales conductive heat-transfer rate.','points'=>2,'sort_order'=>2],
['question'=>'Heat spontaneously moves from lower to higher temperature without work input.','type'=>'true_false','options'=>['True','False'],'correct_answer'=>'False','explanation'=>'Spontaneous heat flow is from higher to lower temperature.','points'=>1,'sort_order'=>3],]);
}}
