<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('experiments',function(Blueprint $t){$t->id();$t->foreignId('created_by')->constrained('users');$t->string('title');$t->string('slug')->unique();$t->string('category');$t->enum('simulation_type',['co2','heat-transfer']);$t->text('summary');$t->longText('theory');$t->json('objectives');$t->json('equipment');$t->json('safety_notes');$t->json('procedure_steps');$t->unsignedInteger('estimated_minutes')->default(45);$t->enum('difficulty',['Beginner','Intermediate','Advanced'])->default('Beginner');$t->boolean('is_published')->default(false);$t->string('accent')->default('cyan');$t->timestamps();});
Schema::create('manuals',function(Blueprint $t){$t->id();$t->foreignId('experiment_id')->constrained()->cascadeOnDelete();$t->string('title');$t->longText('content')->nullable();$t->string('file_path')->nullable();$t->string('version')->default('1.0');$t->boolean('is_required')->default(true);$t->boolean('is_published')->default(true);$t->integer('sort_order')->default(0);$t->foreignId('uploaded_by')->constrained('users');$t->timestamps();});
Schema::create('instructional_videos',function(Blueprint $t){$t->id();$t->foreignId('experiment_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->enum('provider',['upload','youtube','external'])->default('external');$t->string('url')->nullable();$t->string('file_path')->nullable();$t->string('thumbnail_url')->nullable();$t->unsignedInteger('duration_seconds')->nullable();$t->boolean('is_required')->default(true);$t->boolean('is_published')->default(true);$t->integer('sort_order')->default(0);$t->foreignId('uploaded_by')->constrained('users');$t->timestamps();});
Schema::create('quizzes',function(Blueprint $t){$t->id();$t->foreignId('experiment_id')->unique()->constrained()->cascadeOnDelete();$t->string('title');$t->text('instructions')->nullable();$t->unsignedTinyInteger('passing_score')->default(70);$t->unsignedTinyInteger('attempts_allowed')->default(3);$t->unsignedSmallInteger('duration_minutes')->default(15);$t->boolean('is_published')->default(true);$t->timestamps();});
Schema::create('quiz_questions',function(Blueprint $t){$t->id();$t->foreignId('quiz_id')->constrained()->cascadeOnDelete();$t->text('question');$t->enum('type',['single','multiple','true_false','numeric']);$t->json('options')->nullable();$t->json('correct_answer');$t->text('explanation')->nullable();$t->unsignedSmallInteger('points')->default(1);$t->integer('sort_order')->default(0);$t->timestamps();});
Schema::create('quiz_attempts',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('quiz_id')->constrained()->cascadeOnDelete();$t->json('responses');$t->decimal('score',5,2);$t->unsignedInteger('earned_points');$t->unsignedInteger('total_points');$t->boolean('passed');$t->timestamp('started_at')->nullable();$t->timestamp('submitted_at')->nullable();$t->timestamps();});
Schema::create('experiment_attempts',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('experiment_id')->constrained()->cascadeOnDelete();$t->json('parameters');$t->json('results');$t->longText('observations')->nullable();$t->decimal('score',5,2)->nullable();$t->enum('status',['started','completed','submitted'])->default('completed');$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();});
Schema::create('progress_records',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('experiment_id')->constrained()->cascadeOnDelete();$t->timestamp('manual_completed_at')->nullable();$t->timestamp('video_completed_at')->nullable();$t->timestamp('quiz_passed_at')->nullable();$t->timestamp('experiment_completed_at')->nullable();$t->timestamp('report_submitted_at')->nullable();$t->unsignedTinyInteger('overall_percent')->default(0);$t->timestamp('last_activity_at')->nullable();$t->timestamps();$t->unique(['user_id','experiment_id']);});
Schema::create('lab_reports',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('experiment_id')->constrained()->cascadeOnDelete();$t->foreignId('experiment_attempt_id')->nullable()->constrained()->nullOnDelete();$t->string('title');$t->longText('abstract');$t->longText('method');$t->longText('results_discussion');$t->longText('conclusion');$t->string('file_path')->nullable();$t->enum('status',['draft','submitted','graded'])->default('submitted');$t->decimal('score',5,2)->nullable();$t->longText('feedback')->nullable();$t->foreignId('graded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('submitted_at')->nullable();$t->timestamp('graded_at')->nullable();$t->timestamps();});
Schema::create('ai_messages',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('experiment_id')->nullable()->constrained()->nullOnDelete();$t->enum('role',['user','assistant','system']);$t->longText('content');$t->string('provider')->nullable();$t->json('meta')->nullable();$t->timestamps();});
}public function down():void{foreach(['ai_messages','lab_reports','progress_records','experiment_attempts','quiz_attempts','quiz_questions','quizzes','instructional_videos','manuals','experiments'] as $table)Schema::dropIfExists($table);}};
